# Generated by Django 3.2.9 on 2021-11-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_auto_20211129_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='created',
            field=models.DateTimeField(verbose_name='시간'),
        ),
    ]
