# Generated by Django 3.2.9 on 2021-11-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_newpost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='created',
            field=models.DateTimeField(verbose_name='날짜시간'),
        ),
    ]
