# Generated by Django 3.2.9 on 2021-11-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_newpost_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='created',
            field=models.DateTimeField(verbose_name='작성한 날짜 시간'),
        ),
    ]
